name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * SAT"

jobs:
  lockfile:
    name: Update the flake inputs and generate options
    runs-on: linux
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}

      - name: Install Nix
        uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GH_TOKEN }}

      - name: Update flake.lock 
        id: update 
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          pr-title: "Update flake.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
